source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'
pod 'SnapKit', '~> 0.15.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'RealmSwift'
pod 'QRCodeReaderViewController', '~> 4.0.1'
#pod 'RAMAnimatedTabBarController', :git => 'https://github.com/Ramotion/animated-tab-bar'
pod 'Toast', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SwiftDate', '~> 2.0'
pod 'XXPlaceHolder'
pod 'YYText'
pod 'DateTools'
pod 'Kingfisher', '~> 2.0'